<template>
  <div class="paginaLoja">
    <div class="outter-col">
      <div class="inner-row-1">
        <PathPaginaLoja
          :categoriaGeralProduto="categoriaProduto.categoriaGeral"
          :subCategoriaGeralProduto="categoriaProduto.subCategoriaGeral"
          :tipoGeralProduto="categoriaProduto.tipoGeral"
          :subTipoGeralProduto="categoriaProduto.subTipoGeral"
        />
        <hr class="costum-hr" />
      </div>

      <div class="inner-row-2">
        <TextoDescritivo
          :titulo="categoriaProduto.tituloDescritivo"
          :texto="categoriaProduto.textoDescritivo"
        />
      </div>
      <div class="inner-row-3">
        <GridProdutosGrande
          :showcase1="showcase1"
          :showcase2="showcase2"
          :showcase3="showcase3"
          :filterButtons="filterButtons"
        />
      </div>
      <div class="inner-row-4">
        <CarouselDeProdutos :products="products" titulo="Recomendado para si" />
      </div>
    </div>
  </div>
</template>

<script>
import CarouselDeProdutos from "../PaginaProduto/componentes-pagina-produto/Carousel/CarouselDeProdutos.vue";
import GridProdutosGrande from "./componentes-pagina-loja/Grid/GridProdutosGrande.vue";
import TextoDescritivo from "./componentes-pagina-loja/TextoDescritivo.vue";
import PathPaginaLoja from "./componentes-pagina-loja/PathPaginaLoja.vue";
export default {
  components: {
    PathPaginaLoja,
    TextoDescritivo,
    GridProdutosGrande,
    CarouselDeProdutos,
  },

  data() {
    return {
      categoriaProduto: {
        categoriaGeral: "Camas e colchões",
        subCategoriaGeral: "Têxteis para quarto",
        tipoGeral: "Almofadas",
        subTipoGeral: "Almofadas de espuma e espuma memory",
        tituloDescritivo: "Mesas de refeição para exterior",
        textoDescritivo:
          "Aproveite o prazer de jantar fora, em casa. Na nossa gama de mesas de jardim e mesas de refeição para exterior encontra desde mesas dobráveis mais pequenas a grandes mesas extensíveis. Seja um jantar romântico à luz das velas ou banquete no seu jardim ou terraço, a IKEA tem tudo o que precisa para si e todos os convidados. Com uma ampla escolha de estilos e tamanhos diferentes, incluindo conjuntos de cadeiras e mesas, os nossos móveis de refeição para exterior ajudam a criar o seu lugar preferido para comer fora, mesmo na sua casa. Pode escolher entre materiais artificiais que não precisam de manutenção ou o encanto natural da madeira, que não precisa mais do que alguns cuidados de tempos a tempos.",
      },

      products: [
        {
          id: 1,
          productId: "fejka",
          name: "FEJKA",
          type: "Planta Artificial em vaso",
          code: "403.495.31",
          utility: "9cm",
          imageSrc: "https://picsum.photos/360?random=1",
          normalPrice: "",
          currentPrice: 5,
          rating: 4.6,
          ratingCount: 4,
          valueAssembly: 4.8,
          valuePrice: 3.9,
          valueQuality: 4.4,
          valueLooks: 4.6,
          valueExpectations: 4.6,
          packageLength: 70,
          packageWeight: 0.35,
          packageHeight: "",
          packageWidth: "",
          packageQnt: 1,
          link: "fejka",
          variantStock: "success",
          productShowingText:
            "Folhas artificiais com aspeto real que permanecem bonitas e com bom aspeto ano após ano.",
          productHiddenText:
            "Próprio para uso interior e exterior. Ideal se não puder ter uma planta viva mas quiser desfrutar da beleza da natureza.",
          showcaseRatingName: "Ana",
          showcaseRatingDay: "17",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment:
            "Gosto! e para o efeito que queria ficou muito bem",
          showcaseRatingRating: 4,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: "-",
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 9,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "70",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 5,
              clientName: "Ana",
              day: 17,
              month: 5,
              year: 2021,
              generalEvaluation: "Gosto! e para o efeito",
              specificEvaluation:
                "Gosto! e para o efeito que queria ficou muito bem",
              valueAssembly: 5,
              valuePrice: 5,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 5,
            },
            {
              rating: 5,
              clientName: "Katherine",
              day: 25,
              month: 10,
              year: 2020,
              generalEvaluation: "Ótimo",
              specificEvaluation: "Ótimo",
              valueAssembly: 5,
              valuePrice: 5,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 5,
            },
            {
              rating: 5,
              clientName: "Ana Silva",
              day: 26,
              month: 8,
              year: 2020,
              generalEvaluation: "Parece natural",
              specificEvaluation: "Até parece uma flor de tão bonita que é",
              valueAssembly: 4,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 5,
              clientName: "Eleite96",
              day: 9,
              month: 6,
              year: 2020,
              generalEvaluation: "Em perfeitas condições",
              specificEvaluation:
                "Fiz compra online e todos os artigos vieram conforme medidas e aspecto.",
              valueAssembly: 5,
              valuePrice: 5,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 5,
            },
          ],
          favSelected: false,
        },
        {
          id: 2,
          productId: "skogsklover",
          name: "SKOGSKLÖVER",
          type: "Estore de correr",
          code: "403.144.66",
          utility: "120x195 cm",
          imageSrc: "https://picsum.photos/360?random=2",
          normalPrice: "",
          currentPrice: 35,
          rating: 4.2,
          ratingCount: 148,
          valueAssembly: 4.4,
          valuePrice: 4.1,
          valueQuality: 4.1,
          valueLooks: 4.1,
          valueExpectations: 4.3,
          packageLength: 132,
          packageWeight: 1.49,
          packageHeight: 6,
          packageWidth: 7,
          packageQnt: 1,
          link: "skogsklover",
          variantStock: "danger",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Comprimento",
              dimensao: 195,
            },
            {
              tituloMedida: "Superfície",
              dimensao: 23.4,
            },
            {
              tituloMedida: "Largura do rolo",
              dimensao: "123.4",
            },
            {
              tituloMedida: "Largura do tecido",
              dimensao: "120",
            },
          ],
          evaluations: [
            {
              rating: 5,
              clientName: "Maria S",
              day: 21,
              month: 5,
              year: 2021,
              generalEvaluation: "Correspondeu às minhas expectativas",
              specificEvaluation: "Correspondeu às minhas expectativas",
              valueAssembly: 4,
              valuePrice: 5,
              valueQuality: 4,
              valueLooks: 4,
              valueExpectations: 4,
            },
            {
              rating: 5,
              clientName: "Jose",
              day: 1,
              month: 5,
              year: 2021,
              generalEvaluation: "Boa",
              specificEvaluation: "Boa",
              valueAssembly: 5,
              valuePrice: 5,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 5,
            },
            {
              rating: 5,
              clientName: "Ana",
              day: 30,
              month: 4,
              year: 2021,
              generalEvaluation: "Muito bom",
              specificEvaluation:
                "Artigo melhor do que pensava, deixa passar a luz solar tornando o ambiente da divisão agradável. Semi transparente consegue ver se de dentro para fora mas ao contrário não.",
              valueAssembly: 5,
              valuePrice: 5,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 5,
            },
            {
              rating: 5,
              clientName: "Ana",
              day: 28,
              month: 4,
              year: 2021,
              generalEvaluation: "Gosto",
              specificEvaluation:
                "Moro num R/C e é importante ter luz e privacidade. Consigo com este produto ter isso tudo, uma vez que não é opaco, mas da rua ninguém vê o interior o que era uma preocupação.",
              valueAssembly: 5,
              valuePrice: 5,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 5,
            },
          ],
          favSelected: false,
        },
        {
          id: 3,
          productId: "husaro",
          name: "HUSARÖ",
          type: "Poltrona",
          code: "104.678.04",
          utility: "exterior",
          imageSrc: "https://picsum.photos/360?random=3",
          normalPrice: 149,
          currentPrice: 119,
          rating: 4.5,
          ratingCount: 10,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "husaro",
          variantStock: "success",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: 170,
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 23,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "-",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
        {
          id: 4,
          productId: "hauga",
          name: "HAUGA",
          type: "Roupeiro aberto",
          code: "104.678.04",
          utility: "c/3 gavetas 70 x 199 cm",
          imageSrc: "https://picsum.photos/360?random=4",
          normalPrice: 135,
          currentPrice: 112,
          rating: 3,
          ratingCount: 24,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "hauga",
          variantStock: "danger",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: 170,
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 23,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "-",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
        {
          id: 5,
          productId: "bodarp",
          name: "BODARP",
          type: "Porta,",
          code: "104.678.04",
          utility: "verde acinzentado, 60x80 cm",
          imageSrc: "https://picsum.photos/300?random=5",
          normalPrice: 50,
          currentPrice: 30,
          rating: 5,
          ratingCount: 7,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "bodarp",
          variantStock: "success",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: 170,
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 23,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "-",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
        {
          id: 6,
          productId: "bodarp",
          name: "SKYMNINGEN",
          type: "Candeeiro suspenso,",
          code: "104.678.04",
          utility: "branco",
          imageSrc: "https://picsum.photos/300?random=6",
          normalPrice: 79,
          currentPrice: 59,
          rating: 5,
          ratingCount: 3,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "bodarp",
          variantStock: "success",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: 170,
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 23,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "-",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
        {
          id: 7,
          productId: "tangret",
          name: "TRANGET",
          type: "Tapete, tecelagem plana,",
          code: "104.678.04",
          utility: "feito à mão 170x240 cm",
          imageSrc: "https://picsum.photos/300?random=7",
          normalPrice: 249,
          currentPrice: 199,
          rating: 4,
          ratingCount: 10,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "tangret",
          variantStock: "success",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: 170,
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 23,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "-",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
        {
          id: 8,
          productId: "pelarboj",
          name: "PELARBOJ",
          type: "Candeeiro LED de mesa,",
          code: "104.678.04",
          utility: "multicor",
          imageSrc: "https://picsum.photos/300?random=8",
          normalPrice: 20,
          currentPrice: 15,
          rating: 4.5,
          ratingCount: 18,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "pelarboj",
          variantStock: "success",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Maria S",
          showcaseRatingDay: "21",
          showcaseRatingMonth: "5",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Correspondeu às minhas expectativas",
          showcaseRatingRating: 5,
          medidas: [
            {
              tituloMedida: "Altura",
              dimensao: 170,
            },
            {
              tituloMedida: "Diâmetro do vaso",
              dimensao: 23,
            },
            {
              tituloMedida: "Altura da planta",
              dimensao: "-",
            },
            {
              tituloMedida: "Quantidade por embalagem",
              dimensao: "-",
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
        {
          id: 9,
          productId: "bjorkasen",
          name: "BJÖRKÅSEN",
          type: "Suporte p/portátil,",
          code: "204.764.74",
          utility: "bege",
          imageSrc: "https://picsum.photos/300?random=9",
          normalPrice: 19,
          currentPrice: 15,
          rating: 4.7,
          ratingCount: 3,
          valueAssembly: 4,
          valuePrice: 3,
          valueQuality: 5,
          valueLooks: 4,
          valueExpectations: 4,
          packageLength: 170,
          packageWeight: 4.57,
          packageQnt: 1,
          link: "bjorkasen",
          variantStock: "success",
          productShowingText:
            "Os estores reduzem o nível de luz geral e dão privacidade ao impedir que as pessoas no exterior vejam diretamente o interior da divisão.",
          productHiddenText:
            "O estore não tem cordões para maior segurança das crianças. Pode ser montado no interior e no exterior das estruturas da janela ou no teto.",
          showcaseRatingName: "Manuel",
          showcaseRatingDay: "3",
          showcaseRatingMonth: "6",
          showcaseRatingYear: "2021",
          showcaseRatingComment: "Muito bom",
          showcaseRatingRating: 4.7,
          medidas: [
            {
              tituloMedida: "Largura",
              dimensao: 46,
            },
            {
              tituloMedida: "Altura",
              dimensao: 65,
            },
            {
              tituloMedida: "Peso máximo",
              dimensao: 12,
            },
            {
              tituloMedida: "Altura Mínima",
              dimensao: 70,
            },
          ],
          evaluations: [
            {
              rating: 4,
              clientName: "Maria",
              day: 2,
              month: 3,
              year: 2021,
              generalEvaluation: "Vaso Bonito",
              specificEvaluation: "Muito bom para por em salas ou entradas",
              valueAssembly: 5,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 4,
            },
            {
              rating: 2,
              clientName: "Idete",
              day: 26,
              month: 12,
              year: 2020,
              generalEvaluation: "Vaso feio",
              specificEvaluation: "Muito feio e dificil de montar",
              valueAssembly: 1,
              valuePrice: 2,
              valueQuality: 4,
              valueLooks: 1,
              valueExpectations: 1,
            },
            {
              rating: 3,
              clientName: "João",
              day: 20,
              month: 6,
              year: 2021,
              generalEvaluation: "Vaso decente",
              specificEvaluation: "Dificil de montar mas com aspeto bom",
              valueAssembly: 2,
              valuePrice: 4,
              valueQuality: 5,
              valueLooks: 5,
              valueExpectations: 3,
            },
          ],
          favSelected: false,
        },
      ],

      showcase1: [
        {
          nome: "FEJKA",
          tipo: "Planta Artificial em vaso,",
          utilidade: "9cm",
          imagem: "https://picsum.photos/300?random=1",
          precoNormal: 4.5,
          precoAtual: 4,
          rating: 4.5,
          avaliacoes: 8,
          link: "fejka",
        },
        {
          nome: "SKOGSKLÖVER",
          tipo: "Estore de correr,",
          utilidade: "120x195 cm",
          imagem: "https://picsum.photos/300?random=2",
          precoNormal: 35,
          precoAtual: 29,
          rating: 4,
          avaliacoes: 148,
          link: "skogsklover",
        },
        {
          nome: "HUSARÖ",
          tipo: "Poltrona,",
          utilidade: "exterior",
          imagem: "https://picsum.photos/300?random=3",
          precoNormal: 99,
          precoAtual: 85,
          rating: 4.5,
          avaliacoes: 10,
          link: "husaro",
        },
        {
          nome: "HAUGA",
          tipo: "Roupeiro aberto",
          utilidade: "c/3 gavetas, 70x199 cm",
          imagem: "https://picsum.photos/300?random=4",
          precoNormal: 149,
          precoAtual: 119,
          rating: 3,
          avaliacoes: 24,
          link: "hauga",
        },
      ],
      showcase2: [
        {
          nome: "BODARP",
          tipo: "Porta,",
          utilidade: "verde acinzentado, 60x80 cm",
          imagem: "https://picsum.photos/300?random=5",
          precoNormal: 50,
          precoAtual: 30,
          rating: 5,
          avaliacoes: 7,
          link: "bodarp",
        },
        {
          nome: "SKYMNINGEN",
          tipo: "Candeeiro suspenso,",
          utilidade: "branco",
          imagem: "https://picsum.photos/300?random=6",
          precoNormal: 79,
          precoAtual: 59,
          rating: 5,
          avaliacoes: 3,
          link: "smymningen",
        },
        {
          nome: "TRANGET",
          tipo: "Tapete, tecelagem plana,",
          utilidade: "feito à mão várias tonalidades azul 170x240 cm",
          imagem: "https://picsum.photos/300?random=7",
          precoNormal: 249,
          precoAtual: 199,
          rating: 4,
          avaliacoes: 10,
          link: "tangret",
        },
        {
          nome: "PELARBOJ",
          tipo: "Candeeiro LED de mesa,",
          utilidade: "multicor",
          imagem: "https://picsum.photos/300?random=8",
          precoNormal: 20,
          precoAtual: 15,
          rating: 4.5,
          avaliacoes: 18,
          link: "pelarboj",
        },
      ],
      showcase3: [
        {
          nome: "BJÖRKÅSEN",
          tipo: "Suporte p/portátil,",
          utilidade: "bege",
          imagem: "https://picsum.photos/300?random=9",
          precoNormal: 25,
          precoAtual: 19.99,
          rating: 4.5,
          avaliacoes: 3,
          link: "bjorkasen",
        },
        {
          nome: "ÄNGSLILJA",
          tipo: "Capa de edredão + fronha,",
          utilidade: "cinz, 150x200/50x60 cm",
          imagem: "https://picsum.photos/300?random=10",
          precoNormal: 19,
          precoAtual: 15,
          rating: 4,
          avaliacoes: 31,
          link: "angslilja",
        },
        {
          nome: "LISABO",
          tipo: "Mesa, chapa de freixo,",
          utilidade: "140x78 cm",
          imagem: "https://picsum.photos/300?random=11",
          precoNormal: 129,
          precoAtual: 99,
          rating: 4.5,
          avaliacoes: 27,
          link: "lisabo",
        },
        {
          nome: "SLATORP",
          tipo: "Roupeiro aberto,",
          utilidade: "c/3 gavetas, 70x199 cm",
          imagem: "https://picsum.photos/300?random=12",
          precoNormal: 799,
          precoAtual: 699,
          rating: 5,
          avaliacoes: 8,
          link: "slatorp",
        },
      ],

      filterButtons: [
        {
          label: "Quarto",
        },
        {
          label: "Sala",
        },
        {
          label: "Cozinha",
        },
        {
          label: "Escritório",
        },
        {
          label: "Exterior",
        },
        {
          label: "Quarto de criança e bebé",
        },
        {
          label: "Espaço de refeição",
        },
        {
          label: "Entrada",
        },
        {
          label: "Acessórios",
        },
        {
          label: "Acessórios",
        },
      ],
    };
  },
};
</script>

<style lang="scss">
.paginaLoja {
  & .outter-col {
    & .inner-row-1 {
      margin-bottom: 4rem;
    }
    & .inner-row-3 {
      margin-top: 1rem;
    }
  }
}
</style>
